-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 21, 2023 at 07:25 AM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `educoffe_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `coffe`
--

CREATE TABLE `coffe` (
  `id_coffe` int(5) NOT NULL,
  `nama_coffe` varchar(50) NOT NULL,
  `jenis_coffe` varchar(50) NOT NULL,
  `bahan_bahan` text NOT NULL,
  `alat_alat` text NOT NULL,
  `keterangan` text NOT NULL,
  `link_vidio` varchar(100) NOT NULL,
  `status` int(5) NOT NULL,
  `cara_pembuatan` text NOT NULL,
  `gambar` varchar(225) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `coffe`
--

INSERT INTO `coffe` (`id_coffe`, `nama_coffe`, `jenis_coffe`, `bahan_bahan`, `alat_alat`, `keterangan`, `link_vidio`, `status`, `cara_pembuatan`, `gambar`) VALUES
(2, 'Creamy Cappucino', 'cappucino', '1. Kopi bubuk\r\n2. Air panas\r\n3. Gula\r\n4. Krim atau susu\r\n5. Pemanis tambahan (opsional), seperti sirup vanila atau karamel sesuai selera.', '1. Cangkir atau gelas : Tempat untuk menyajikan creamy coffee.\r\n2. Sendok pengaduk : Untuk mencampur kopi dengan bahan-bahan lainnya.\r\n3. Peralatan penyaring kopi : Misalnya, pembuat kopi atau alat seduh seperti French press atau pour-over, tergantung pada jenis kopi yang diinginkan.\r\n4. Teko atau pemanas air : Untuk menyediakan air panas yang diperlukan untuk menyeduh kopi.\r\n5. Gula atau sendok takar : Untuk menambahkan gula sesuai selera.\r\n6. Panci kecil atau microwave (opsional) : Untuk menghangatkan krim atau susu jika diperlukan.\r\n7. Alat pengocok atau mesin cappuccino (opsional) : Jika ingin membuat creamy coffee dengan busa yang lebih banyak.\r\n8. Gelas ukur (opsional) : Untuk mengukur jumlah krim, susu, atau sirup yang digunakan.\r\n\r\nDengan alat-alat ini, Anda dapat dengan mudah menyiapkan creamy coffee sesuai dengan selera Anda.', 'Creamy coffee adalah minuman kopi yang diperkaya dengan krim atau susu, memberikan tekstur lembut dan rasa yang lebih kaya pada kopi.', 'https://www.youtube.com/watch?v=c9UORdMZ2cw', 0, '1. Seduh Kopi:\r\nCampur 2 sendok teh kopi bubuk dengan 1 cangkir air panas.\r\nAduk rata hingga kopi larut.\r\n\r\n2. Tambahkan Gula:\r\nTambahkan gula sesuai selera.\r\nAduk lagi hingga gula larut.\r\n\r\n3. Tambahkan Krim atau Susu:\r\nTuangkan 2 sendok makan krim atau susu ke dalam kopi.\r\nAduk hingga merata.\r\n\r\n4. Opsi Sirup (Jika diinginkan):\r\nJika suka, tambahkan sirup vanila atau karamel untuk memberikan rasa tambahan.\r\nAduk hingga tercampur dengan baik.\r\n\r\n5. Sajikan:\r\nTuangkan creamy coffee ke dalam cangkir atau gelas.\r\n\r\n6. Hias (Opsional):\r\nJika ingin, hias dengan bubuk cokelat, serbuk kayu manis, atau whipped cream.\r\n\r\n7. Nikmati:\r\nCreamy coffee siap dinikmati! Minum hangat-hangat dan nikmati kelezatannya.', 'creamy-cappucino.jpg'),
(3, 'Perfect Cappucino', 'cappucino', '1. espresso segar\r\n2. susu panas\r\n3. dan busa susu yang lembut.', '1. Mesin Espresso : Untuk membuat espresso yang kuat dan berkualitas.\r\n   \r\n2. Penggiling Kopi : Agar dapat menggunakan kopi segar, Anda memerlukan penggiling kopi untuk menghasilkan bubuk kopi dengan konsistensi yang baik.\r\n\r\n3. Steaming Wand atau Mesin Pengukus Susu : Untuk menghasilkan susu panas dan busa susu yang diperlukan dalam pembuatan cappuccino.\r\n\r\n4. Termometer : Untuk mengukur suhu susu dan memastikan sesuai dengan kebutuhan untuk menghasilkan busa susu yang sempurna.\r\n\r\n5. Cangkir Espresso : Tempat untuk menyajikan espresso.\r\n\r\n6. angkir Cappuccino : Cangkir berukuran sedang untuk menyajikan cappuccino dengan proporsi yang tepat antara espresso, susu, dan busa susu.\r\n\r\n7. Sendok : Untuk mencampur espresso dengan busa susu dan memberikan sentuhan akhir pada minuman.', 'Perfect cappuccino adalah minuman kopi yang sempurna dengan perbandingan yang tepat antara espresso, susu panas, dan busa susu, menciptakan harmoni rasa dan tekstur yang khas.', 'https://www.youtube.com/watch?v=gvPetTPFsZM', 0, '1. Persiapkan Mesin Espresso :\r\n   - Panaskan mesin espresso dan siapkan dua shot espresso. Pastikan kopi yang digunakan adalah kopi berkualitas tinggi.\r\n\r\n2. Penggiling Kopi :\r\n   - Giling kopi segar dengan ukuran bubuk yang sesuai dengan mesin espresso Anda.\r\n\r\n3. Panaskan Susu :\r\n   - Tuangkan susu ke dalam cangkir pengukus dan panaskan hingga sekitar 65-70 derajat Celsius menggunakan termometer sebagai panduan.\r\n\r\n4. Buat Busa Susu :\r\n   - Gunakan steaming wand atau mesin pengukus susu untuk membuat busa susu yang kental dan lembut. Pastikan sisi busa susu diletakkan di atas espresso untuk memberikan lapisan yang khas pada cappuccino.\r\n\r\n5. Persiapkan Cangkir :\r\n   - Pemanaskan cangkir cappuccino dengan air panas, lalu buang airnya.\r\n\r\n6. Tuang Espresso :\r\n   - Tuangkan dua shot espresso ke dalam cangkir espresso yang sudah dipanaskan.\r\n\r\n7. Tambahkan Susu dan Busa Susu :\r\n   - Tuangkan susu panas ke dalam cangkir espresso dengan hati-hati, lalu tambahkan busa susu di atasnya. \r\n\r\n8. Hias (Opsional) :\r\n   - Jika suka, taburkan sedikit bubuk cokelat atau kayu manis di atas busa susu untuk memberikan sentuhan akhir.\r\n\r\n9. Nikmati :\r\n   - Segera nikmati perfect cappuccino Anda! Jangan lupa mencicipi perpaduan sempurna antara espresso, susu, dan busa susu.', 'perfect-cappucino.jpg'),
(4, 'Easy Cappucino', 'cappucino', '1. Kopi instan atau kopi bubuk : 1-2 sendok teh, tergantung seberapa kuat Anda ingin kopi.\r\n2. Air panas : 1 cangkir.\r\n3. Susu : 1/2 cangkir hingga 1 cangkir, tergantung selera.\r\n4. Gula : Secukupnya, sesuai selera.\r\n5. Bubuk kayu manis atau bubuk cokelat (opsional) : Untuk hiasan dan tambahan rasa.', '1. Gelas atau cangkir: Tempat untuk menyajikan cappuccino.\r\n\r\n2. Sendok: Untuk mengaduk dan mencampur bahan-bahan.\r\n\r\n3. Pemanas air: Untuk membuat air panas yang diperlukan untuk menyeduh kopi instan.', 'Easy cappuccino adalah varian cappuccino yang mudah disiapkan tanpa peralatan khusus, menggunakan kopi instan atau kopi bubuk, air panas, susu, dan gula sesuai selera.', 'https://www.youtube.com/watch?v=mydxhGG_g4o', 1, '1. Seduh Kopi :\r\n   - Campur 1-2 sendok teh kopi instan atau kopi bubuk dengan 1 cangkir air panas.\r\n   - Aduk hingga kopi larut sepenuhnya.\r\n\r\n2. Panaskan Susu :\r\n   - Panaskan susu hingga cukup panas, namun tidak sampai mendidih. Ini dapat dilakukan dengan menggunakan panci kecil atau microwave.\r\n\r\n3. Buat Busa Susu (Opsional) :\r\n   - Jika Anda suka, Anda dapat membuat sedikit busa susu dengan mengocok susu menggunakan sendok atau mesin pengocok sederhana.\r\n\r\n4. Campurkan Kopi dan Susu :\r\n   - Tuangkan kopi yang sudah diseduh ke dalam cangkir.\r\n   - Tambahkan susu panas ke dalam cangkir dengan kopi. \r\n\r\n5. Tambahkan Gula :\r\n   - Tambahkan gula sesuai selera dan aduk hingga larut.\r\n\r\n6. Hias (Opsional) :\r\n   - Jika suka, taburkan bubuk kayu manis atau bubuk cokelat di atasnya untuk memberikan sentuhan akhir.\r\n\r\n7. Nikmati :\r\n   - Easy cappuccino siap dinikmati! Segera nikmati kelezatan cappuccino yang mudah dan praktis ini.', 'easy-cappucino.jpg'),
(5, 'Iced caramel cappucino', 'cappucino', '1. Espresso atau kopi yang sangat kuat :** 1-2 shot.\r\n2. Susu dingin : 1 cangkir.\r\n3. Es batu : Secukupnya.\r\n4. Sirup karamel : 2 sendok makan (atau sesuai selera).\r\n5. Whipped cream (opsional) : Untuk hiasan.', '1. Mesin Espresso atau Alat Seduh Kopi: Untuk membuat espresso atau kopi yang sangat kuat.\r\n2. Gelas atau Cangkir untuk Iced Coffee: Gelas yang cukup besar untuk menampung es dan minuman.\r\n3. Sendok Pengaduk: Untuk mencampur bahan-bahan.\r\n4. Penggiling Kopi (opsional): Jika Anda menggunakan kopi bubuk, penggiling kopi diperlukan untuk mendapatkan kehalusan yang diinginkan.\r\n5. Shaker atau Blender (opsional): Untuk mencampur semua bahan dengan es secara merata.\r\n6. Es Batu: Untuk memberikan efek dingin pada minuman.\r\n7. Cetakan Es (opsional): Jika ingin menggunakan es yang berbeda seperti es kopi.\r\n8. Gantang atau Sendok Pengukur: Untuk mengukur sirup karamel.', 'Iced caramel cappuccino adalah minuman kopi yang dingin dengan paduan espresso, susu dingin, sirup karamel, dan es batu, memberikan rasa segar dan kelembutan dengan sentuhan manis karamel.', 'https://www.youtube.com/watch?v=fHnrBJJM7J8', 1, '1. Siapkan Espresso atau Kopi:\r\n   - Seduh 1-2 shot espresso atau kopi yang sangat kuat. Biarkan dingin atau dinginkan di dalam kulkas.\r\n\r\n2. Campurkan Susu dan Sirup Karamel:\r\n   - Dalam gelas besar atau shaker, campurkan susu dingin dengan 2 sendok makan sirup karamel.\r\n  \r\n3. Tambahkan Espresso atau Kopi:\r\n   - Tuangkan espresso atau kopi yang sudah diseduh ke dalam campuran susu dan sirup karamel. Aduk rata.\r\n\r\n4. Tambahkan Es Batu:\r\n   - Isi gelas dengan es batu secukupnya untuk memberikan kesegaran pada minuman.\r\n\r\n5. Kocok atau Aduk Rata (Opsional):\r\n   - Jika suka, kocok atau aduk rata campuran kopi, susu, dan sirup dengan menggunakan shaker atau sendok.\r\n\r\n6. Hias dan Sajikan:\r\n   - Jika diinginkan, tambahkan whipped cream di atasnya untuk hiasan.\r\n   - Sajikan segera dan nikmati Iced Caramel Cappuccino yang menyegarkan!', 'ice-caramel-cappucino.jpg'),
(6, 'Mocha Cappucino', 'cappucino', 'Berikut adalah bahan-bahan yang dibutuhkan untuk membuat mocha cappuccino:\r\n\r\n1. Espresso atau kopi yang sangat kuat:1-2 shot.\r\n2. Kakao bubuk: 1-2 sendok teh.\r\n3. Gula: Secukupnya, sesuai selera.\r\n4. Susu:1 cangkir.\r\n5. Whipped cream (opsional): Untuk hiasan.', '1. Mesin Espresso atau Alat Seduh Kopi: Untuk membuat espresso atau kopi yang sangat kuat.\r\n2. Penggiling Kopi (opsional): Jika Anda menggunakan kopi bubuk, penggiling kopi diperlukan untuk mendapatkan kehalusan yang diinginkan.\r\n3. Sendok atau Sendok Pengukur: Untuk mengukur kakao bubuk dan gula.\r\n4. Pemanas Susu atau Steaming Wand: Untuk menghangatkan dan membuat busa susu.\r\n5. Cangkir atau Gelas: Tempat untuk menyajikan mocha cappuccino.\r\n6. Whipped Cream Dispenser (opsional): Jika ingin menambahkan whipped cream.', 'Mocha cappuccino adalah minuman kopi yang memadukan espresso yang kuat dengan rasa cokelat kakao dan susu, seringkali dihiasi dengan whipped cream untuk menciptakan pengalaman kopi yang kaya dan beraroma.', 'https://www.youtube.com/watch?v=Oj0u4DoOyL0', 1, '1. Seduh Espresso atau Kopi:\r\n   - Seduh 1-2 shot espresso atau kopi yang sangat kuat. Pastikan rasa kopi sesuai dengan preferensi Anda.\r\n\r\n2. Persiapkan Kakao Bubuk dan Gula:\r\n   - Campurkan kakao bubuk dan gula secukupnya di dalam cangkir atau gelas.\r\n\r\n3. Tambahkan Espresso:\r\n   - Tuangkan espresso yang sudah diseduh ke dalam campuran kakao dan gula. Aduk hingga larut.\r\n\r\n4. Panaskan dan Busakan Susu:\r\n   - Panaskan susu hingga cukup panas, namun tidak sampai mendidih.\r\n   - Gunakan steaming wand atau pemanas susu untuk membuat busa susu yang kental.\r\n\r\n5. Tambahkan Susu ke Kopi:\r\n   - Tuangkan susu panas ke dalam cangkir, mengisi sisa cangkir setelah espresso.\r\n   - Biarkan busa susu berada di atasnya untuk menciptakan lapisan cappuccino yang khas.\r\n\r\n6. Aduk dan Hiasi (Opsional):\r\n   - Aduk rata campuran susu dan espresso.\r\n   - Jika suka, tambahkan whipped cream di atasnya untuk hiasan.\r\n\r\n7. Nikmati:\r\n   - Mocha cappuccino siap dinikmati! Segera nikmati gabungan rasa kopi yang kuat dengan kelezatan cokelat dan kelembutan susu.', 'mocha-cappucino.jpg'),
(7, 'Espresso Ristretto', 'espresso', '1. Kopi yang berkualitas tinggi: Biji kopi segar atau kopi bubuk yang baru digiling.\r\n2. Air bersih: Untuk menyeduh kopi.\r\n3. (Opsional) Gula atau pemanis lainnya: Sesuai selera.', '1. Mesin espresso. Mesin espresso adalah alat utama yang digunakan untuk mengekstrak kopi dan menghasilkan espresso. Beberapa mesin espresso populer untuk membuat ristretto antara lain La Marzocco, Rancilio, dan Gaggia.\r\n\r\n2. Grinder kopi. Grinder diperlukan untuk menggiling biji kopi menjadi serbuk halus sebelum diekstrak menjadi espresso. Grinder yang baik sangat penting untuk mendapatkan ekstraksi kopi yang konsisten. Contoh grinder yang cocok untuk espresso antara lain Mazzer, Baratza, dan Eureka.\r\n\r\n3. Tamper. Tamper digunakan untuk menekan atau memadatkan serbuk kopi yang sudah digiling ke dalam portafilter. Tamper yang terbuat dari stainless steel adalah pilihan terbaik.\r\n\r\n4. Portafilter dan filter basket. Portafilter adalah bagian pegangan tempat filter basket ditempatkan. Filter basket berfungsi sebagai tempat meletakkan kopi bubuk sebelum diekstrak. Biasanya terdapat 2 jenis filter basket, single dan double.\r\n\r\n5. Cangkir espresso. Cangkir khusus espresso digunakan untuk menyajikan espresso ristretto yang dihasilkan agar bisa dinikmati.\r\n\r\n6. Alat pengukur/timbangan kopi. Timbangan elektrik sangat bermanfaat agar bisa menakar jumlah kopi yang digunakan secara konsisten. Stopwatch juga diperlukan untuk mengukur waktu ekstraksi.', 'Espresso ristretto adalah espresso dengan volume ekstraksi kopi yang dikeluarkan lebih sedikit dari espresso normal, dengan cita rasa yang lebih kuat.', 'https://www.youtube.com/watch?v=Oz_iT5rmgV8', 0, '1. Siapkan alat-alatnya seperti mesin espresso, grinder, tamper, portafilter, dan cangkir. Pastikan semuanya dalam kondisi bersih.\r\n\r\n2. Atur grind size kopi agak halus pada grinder. Hal ini karena ristretto menggunakan waktu ekstraksi yang lebih cepat. \r\n\r\n3. Timbang dosis kopi sekitar 15-18 gram, lalu giling menggunakan grinder.\r\n\r\n4. Ketuk-ketuk portafilter agar serbuk kopi merata, lalu padatkan dengan tamper dengan tekanan 30 lbs.\r\n\r\n5. Pasang portafilter pada grup head mesin espresso dan tempatkan cangkir di bawahnya.\r\n\r\n6. Hidupkan mesin espresso dan atur waktu ekstraksi hanya sekitar 15-20 detik saja.\r\n\r\n7. Matikan mesin dan sajikan espresso ristretto segera agar aromanya tetap terjaga.\r\n\r\n8. Hiasi dengan latte art jika mau. Ristretto siap dinikmati!\r\n', 'risretto.jpg'),
(8, 'Espresso Lungo', 'espresso', '1. Kopi espresso (Arabika, Robusta)\r\n2. Air\r\n3. Susu\r\n4. Gula\r\n5. Krim kocok', '1. Mesin Espresso\r\nMesin espresso adalah peralatan utama untuk mengekstrak biji kopi menjadi espresso lungo.\r\n\r\n2. Grinder Kopi\r\nDigunakan untuk menggiling biji kopi menjadi serbuk halus sebelum diekstrak mesin espresso.\r\n\r\n3. Tamper\r\nAlat untuk menekan atau memadatkan kopi serbuk ke dalam filter basket agar ekstraksi maksimal.  \r\n\r\n4. Portafilter\r\nPegangan tempat meletakkan filter basket berisi kopi bubuk.\r\n\r\n5. Filter Basket \r\nTempat meletakkan kopi bubuk yang akan diekstrak.\r\n\r\n6. Cangkir Espresso\r\nDigunakan untuk menyajikan espresso lungo yang sudah jadi agar siap dinikmati.\r\n\r\n7. Milk pitcher dan milk frother\r\nAlat untuk mengocok susu membuat busa halus sebagai topping espresso lungo.\r\n', 'Espresso lungo adalah varian espresso dengan volume kopi yang diekstrak lebih banyak dari espresso normal sehingga memiliki cita rasa yang lebih ringan dan disajikan dalam cangkir berukuran besar.', 'https://youtube.com/watch?v=MZV88PLBBFY', 0, '1. Siapkan alat dan bahan yang diperlukan seperti mesin espresso, grinder, biji kopi, gula, dan cangkir.\r\n\r\n2. Atur grind size agak kasar pada grinder kopi.\r\n\r\n3. Timbang takaran kopi sekitar 16-20 gram dan giling menggunakan grinder. \r\n\r\n4. Ketuk-ketuk portafilter lalu padatkan kopi menggunakan tamper dengan tekanan 30 lbs.\r\n\r\n5. Pasang portafilter pada grup head mesin espresso dan letakkan cangkir di bawahnya.\r\n\r\n6. Hidupkan mesin espresso. Atur waktu ekstraksi lebih lama, sekitar 25-30 detik.\r\n\r\n7. Matikan mesin espresso jika volume kopi sudah mencapai 80-90 ml dan beri gula sesuai selera. \r\n\r\n8. Hias espresso lungo dengan latte art agar penyajiannya lebih menarik.\r\n\r\n9. Sajikan espresso lungo segera agar tetap hangat dan nikmat. ya.', 'lungo.jpg'),
(9, 'Single Shot', 'espresso', '1. Kopi espresso (Arabika, Robusta)\r\n2. Air\r\n3. Gula', '1. Mesin Espresso\r\nMesin espresso manual atau otomatis digunakan untuk mengekstrak kopi.\r\n\r\n2. Grinder \r\nUntuk menggiling biji kopi espresso menjadi serbuk halus.\r\n\r\n3. Tamper\r\nAlat untuk memadatkan kopi ke dalam filter basket agar ekstraksi maksimal.\r\n\r\n4. Portafilter\r\nTempat meletakkan filter basket yang sudah berisi kopi bubuk.\r\n\r\n5. Filter Basket\r\nTempat bubuk kopi yang akan diekstrak mesin espresso.\r\n\r\n6. Cangkir Espresso\r\nDigunakan untuk menyajikan espresso yang sudah jadi.\r\n\r\n7. Tambahan: gelas ukur dan stopwatch\r\nUntuk menakar takaran dan mengukur waktu ekstraksi.', 'Espresso single shot adalah espresso yang dibuat dengan mengekstrak 7-9 gram kopi dengan 1 shot air panas dalam waktu 25-30 detik.', 'https://www.youtube.com/watch?v=24g9Ff8OQik', 1, '1. Siapkan mesin espresso dan atur temperature serta tekanannya.\r\n\r\n2. Giling biji kopi espresso dengan grinder kira-kira 7-9 gram.\r\n\r\n3. Ketuk-ketuk portafilter lalu padatkan kopi yang sudah digiling menggunakan tamper.\r\n\r\n4. Pasang portafilter yang sudah berisi kopi ke grup head mesin espresso.\r\n\r\n5. Letakkan gelas espresso di bawah portafilter lalu hidupkan mesin espresso.\r\n\r\n6. Atur waktu ekstraksi kira-kira 25-30 detik agar mengekstrak kopi maksimal dan hasilkan 1 shot espresso.  \r\n\r\n7. Matikan mesin espresso dan sajikan espresso single shot segera.\r\n\r\n8. Boleh tambah gula atau krimer sesuai selera serta hias dengan latte art.', 'oneshoot.jpeg'),
(10, 'double shoot', 'espresso', '1. Kopi espresso (Arabika, Robusta)\r\n2. Air\r\n3. Gula', '1. Mesin Espresso\r\nMesin espresso manual atau otomatis digunakan untuk mengekstrak kopi.\r\n\r\n2. Grinder \r\nUntuk menggiling biji kopi espresso menjadi serbuk halus.\r\n\r\n3. Tamper\r\nAlat untuk memadatkan kopi ke dalam filter basket agar ekstraksi maksimal.\r\n\r\n4. Portafilter\r\nTempat meletakkan filter basket yang sudah berisi kopi bubuk.\r\n\r\n5. Filter Basket\r\nTempat bubuk kopi yang akan diekstrak mesin espresso.\r\n\r\n6. Cangkir Espresso\r\nDigunakan untuk menyajikan espresso yang sudah jadi.\r\n\r\n7. Tambahan: gelas ukur dan stopwatch\r\nUntuk menakar takaran dan mengukur waktu ekstraksi.', 'Espresso double shot adalah jenis espresso yang dibuat dengan mengekstrak 14-18 gram kopi dengan 2 shot air panas dalam waktu 25-30 detik.', 'https://www.youtube.com/watch?v=24g9Ff8OQik', 1, '1. Siapkan alat dan bahan, seperti mesin espresso, grinder, 14-18 gram biji kopi, gula, dan gelas espresso.\r\n\r\n2. Atur mesin espresso pada suhu 92-96 derajat Celcius serta tekanan 9 bar.\r\n\r\n3. Giling kopi dengan grinder hingga menjadi serbuk halus. \r\n\r\n4. Ketuk-ketuk portafilter lalu padatkan serbuk kopi menggunakan tamper dengan tekanan 30 lbs.\r\n\r\n5. Pasang portafilter pada grup head mesin espresso dan letakkan gelas di bawahnya.\r\n\r\n6. Hidupkan mesin espresso. Atur waktu ekstraksi 25-30 detik agar didapatkan 2 shot espresso.\r\n\r\n7. Setelah ekstraksi, matikan mesin. Tambahkan gula jika suka.\r\n\r\n8. Hiasi espresso double shot dengan latte art lalu sajikan selagi hangat.', 'doubleshoot.jpeg'),
(11, 'Espresso Machiato', 'espresso', '1. Espresso (single atau double shot)\r\n2. Susu cair/susu evaporasi\r\n3. Krim kocok\r\n4. Sirup (opsional)\r\n5. Topping taburan (opsional)', '1. Mesin Espresso\r\nUntuk mengekstrak kopi menjadi espresso sebagai base minuman.\r\n\r\n2. Grinder\r\nDigunakan untuk menggiling biji kopi espresso.\r\n\r\n3. Tamper\r\nUntuk memadatkan kopi bubuk ke dalam filter basket.\r\n\r\n4. Pitcher dan Milk Frother\r\nUntuk mengocok susu hingga berbusa halus. \r\n\r\n5. Gelas Espresso\r\nTempat penyajian espresso macchiato agar siap disajikan.\r\n\r\n6. Sendok\r\nSendok stainless steel untuk menyendok & menuang susu.\r\n\r\n7. Topping Shaker\r\nBotol kecil berisi bubuk kopi atau coklat untuk taburan topping.\r\n\r\n8. Timbangan Digital\r\nUntuk menakar takaran bahan agar hasil konsisten.', 'Espresso macchiato adalah minuman espresso yang diberi sedikit susu dan lapisan busa krim yang tebal di atasnya.', 'https://www.youtube.com/watch?v=_3lhqCgFjdc', 1, '1. Sediakan gelas espresso yang sudah dihangatkan. \r\n\r\n2. Buat single atau double shot espresso panas menggunakan mesin espresso.\r\n\r\n3. Kocok susu cair menggunakan milk frother hingga berbusa halus dan creamy.\r\n\r\n4. Tuang susu yang sudah dikocok sebanyak 1-2 sendok makan ke atas espresso panas.\r\n\r\n5. Tambahkan krim kocok dingin di atas lapisan susu tadi hingga mencapai 1-2 cm dan membentuk busa yang tebal.\r\n\r\n6. Buat pola atau lukisan untuk memperindah tampilan (opsional).\r\n\r\n7. Taburkan sedikit bubuk coklat atau kopi di atas busa sebagai topping. \r\n\r\n8. Sajikan espresso macchiato segera selagi masih hangat.\r\n\r\n9. Espresso macchiato siap dinikmati.', 'espresso-machiato.jpg'),
(12, 'Long Black', 'black coffe', '1. Espresso\r\n2. Air panas', '1. Mesin Espresso\r\nDigunakan untuk mengekstrak biji kopi menjadi espresso.\r\n\r\n2. Grinder \r\nUntuk menggiling biji kopi menjadi serbuk halus sebelum diekstrak.\r\n\r\n3. Tamper\r\nAlat pemadat kopi bubuk di dalam filter basket.\r\n\r\n4. Portafilter\r\nTempat meletakkan filter basket berisi kopi bubuk.\r\n\r\n5. Filter Basket\r\nTempat bubuk kopi yang akan diekstrak mesin espresso.\r\n\r\n6. Gelas Tahan Panas\r\nDigunakan untuk menyajikan long black.\r\n\r\n7. Panci Kecil\r\nUntuk memanaskan air sampai suhu yang dibutuhkan.\r\n\r\n8. Sendok Pengaduk\r\nUntuk mengaduk long black agar tercampur rata.', 'Long black adalah minuman espresso yang dibuat dengan menambahkan air panas ke dalam shot espresso sehingga memiliki rasa yang lebih ringan.', 'https://www.youtube.com/watch?v=pbIuhZ_d7ew', 0, '1. Seduh Espresso:\r\nPersiapkan double shot espresso dengan menggunakan mesin espresso atau alat seduh kopi.\r\n\r\n2. Panaskan Air:\r\nPanaskan air hingga sekitar 60-90 °C. Air panas ini nantinya akan ditambahkan ke dalam espresso.\r\n\r\n3. Persiapkan Gelas atau Cangkir:\r\nGunakan gelas cangkir dengan ukuran yang sesuai dengan porsi long black yang diinginkan.\r\n\r\n4.Tuangkan Espresso:\r\nTuangkan double shot espresso ke dalam gelas atau cangkir yang telah disiapkan.\r\n\r\n5.Tambahkan Air Panas:\r\nTambahkan air panas ke dalam espresso. Perbandingan antara espresso dan air dapat disesuaikan dengan selera, tetapi umumnya berkisar antara 1:1 hingga 1:2.\r\n\r\n6.Jangan Aduk (Opsional):\r\nLong black biasanya tidak diaduk untuk mempertahankan crema espresso di atasnya, tetapi ini adalah preferensi pribadi.\r\n\r\n7.Nikmati:\r\nLong black siap dinikmati! Sajikan segera dan nikmati cita rasa kopi yang kuat dan beraroma.', 'long-black.jpg'),
(13, 'Americano', 'black coffe', '1. Espresso shot: 1 atau 2 shot, tergantung selera.\r\n2. Air panas: 120-240 ml, tergantung selera.\r\n3. (Opsional) Gula atau pemanis lainnya: Sesuai selera', '1. Mesin Espresso atau Alat Seduh Kopi: Untuk membuat espresso shot.\r\n2. Gelas atau Cangkir: Tempat menyajikan Americano.\r\n3. Pemanas Air: Untuk menyediakan air panas yang diperlukan.\r\n4. Timbangan (opsional): Jika ingin mengukur takaran kopi secara tepat.\r\n5. Timer (opsional): Untuk mengukur waktu ekstraksi espresso.\r\n6. Sendok atau Pengaduk: Untuk mencampur air panas dan espresso.\r\n7. (Opsional) Gula atau pemanis lainnya: Sesuai selera.', 'Americano adalah minuman kopi yang terdiri dari espresso yang dilarutkan dengan air panas, menciptakan rasa yang lebih ringan dan mirip dengan kopi hitam tradisional.', 'https://www.youtube.com/watch?v=LEtBjtbuRWA', 0, '1. Panaskan Air:\r\nPanaskan air hingga mencapai suhu yang diinginkan, biasanya antara 80-94 °C.\r\n\r\n2. Siapkan Gelas atau Cangkir:\r\nGunakan gelas atau cangkir yang cukup besar untuk menampung volume air dan espresso.\r\n\r\n3. Tuangkan Espresso ke dalam Gelas:\r\nTuangkan espresso yang sudah diseduh ke dalam gelas atau cangkir.\r\n\r\n4. Tambahkan Air Panas:\r\nTambahkan air panas ke dalam gelas, menciptakan rasio espresso dan air sesuai dengan selera Anda. Rasio yang umum adalah 1:1 hingga 1:2 (espresso:air).\r\n\r\n5. Aduk (Opsional):\r\nJika diinginkan, aduk campuran espresso dan air untuk meratakan rasa.\r\n\r\n6. Tambahkan Pemanis (Opsional):\r\nJika Anda suka, tambahkan gula atau pemanis lainnya sesuai selera.\r\n\r\n7. Nikmati:\r\nAmericano siap dinikmati! Sajikan segera dan nikmati minuman kopi yang lebih ringan dengan sentuhan espresso.', 'americano.jpg'),
(14, 'Turkish Coffe', 'black coffe', '1. Kopi Turkish yang halus: Bubuk kopi yang sangat halus, hampir seperti bedak.\r\n2. Air: Secukupnya sesuai dengan porsi kopi yang diinginkan.\r\n3. Gula (opsional): Sesuai selera.\r\n4. Cardamom (opsional): Untuk memberikan aroma dan rasa tambahan.', '1. Cezve (Ibrik): Alat tradisional Turki berbentuk cangkir berpegangan panjang dengan leher yang sempit.\r\n2. Sendok Pengaduk: Sendok panjang untuk mencampur kopi dan air selama proses penyeduhan.\r\n3. Timbangan: Opsional, untuk mengukur kopi dengan tepat.\r\n4. Pemanas atau Kompor: Untuk memanaskan air dan menyeduh kopi.\r\n5. Gelas Turkish Coffee (Finjan): Gelas khusus untuk menyajikan Turkish coffee.\r\n5. Saji atau Alas:\r\n- Rengginang (Sini): Tempat menaruh cezve dan gelas selama proses penyeduhan.\r\n- Nampan atau Saji: Untuk menyajikan Turkish coffee dengan rapi.', 'Turkish coffee adalah minuman kopi khas Turki yang diseduh dengan bubuk kopi halus, air, dan kadang-kadang gula, menciptakan minuman pekat dan beraroma yang disajikan dalam cangkir khusus.', 'https://www.youtube.com/watch?v=qmKtgzFk0dA', 1, '1.Siapkan Cezve:\r\nMasukkan bubuk kopi, air, dan gula (jika digunakan) ke dalam cezve sesuai jumlah yang diinginkan.\r\n\r\n2.Tambahkan Cardamom (Opsional):\r\nJika menggunakan cardamom, tambahkan biji yang telah dihancurkan ke dalam campuran kopi.\r\n\r\n3.Aduk Rata:\r\nAduk campuran secara perlahan untuk meratakan kopi, air, dan gula.\r\n\r\n4.Panaskan Cezve:\r\nTempatkan cezve di atas api dengan panas sedang-hingga-kecil. Hindari membiarkan campuran mendidih.\r\n\r\n5.Penyeduhan:\r\nBiarkan campuran mencapai hampir mendidih, kemudian angkat dari api sebentar sebelum proses penyeduhan selesai.\r\n\r\n6.Panaskan Ulang (Opsional):\r\nUlangi proses pemanasan dan penyeduhan beberapa kali untuk mendapatkan kekentalan yang diinginkan.\r\n\r\n7.Sajikan:\r\nTuangkan Turkish coffee ke dalam gelas Turkish coffee, saring sedimen jika perlu, dan nikmati dengan pelan-pelan.\r\n\r\n8.Tambahkan Gula (Opsional):\r\nJika Anda suka, tambahkan gula sesuai selera setelah menyajikan.\r\n\r\nTurkish coffee membutuhkan kesabaran dan perhatian terhadap proses penyeduhan yang khas, menghasilkan minuman kopi yang kaya dan pekat dengan aroma yang unik.\r\n\r\n\r\n\r\n\r\n\r\n\r\n', 'turkish-coffe.jpg'),
(15, 'Original Irish Coffe', 'irish coffe', 'Bahan-bahan:\r\n\r\n1. Kopi hitam yang kuat (1 cangkir)\r\n2. Whiskey Irlandia (1 1/2 ons atau sekitar 45 ml)\r\n3. Gula (1 sendok teh, atau sesuai selera)\r\n4. Whipped cream (krim kocok) yang sudah dikocok kaku', '1. Gelas Pemanas (Irish Coffee Glass): Gunakan gelas khusus untuk Irish Coffee yang biasanya tahan panas dan memiliki ruang yang cukup untuk kopi, whiskey, dan whipped cream.\r\n\r\n2. Sendok:\r\n   - Sendok Pengaduk: Digunakan untuk mencampur whiskey dan gula dengan kopi.\r\n   - Sendok Tambahkan Whipped Cream: Digunakan untuk perlahan-lahan menambahkan whipped cream di atas kopi.\r\n\r\n3. Pemanas Air (Opsional): Digunakan untuk memanaskan gelas sebelum disajikan.\r\n\r\n4. Mesin Pembuat Kopi atau French Press: Untuk menyeduh kopi hitam yang kuat.\r\n\r\n5. Timbangan atau Jigger: Untuk mengukur jumlah whiskey dengan tepat.\r\n\r\n6. Alat Pencampur atau Sendok Pengocok (Opsional): Jika Anda ingin mencampur whiskey dan gula dengan lebih baik sebelum menuangkan ke dalam kopi.\r\n\r\n7. Alat Pencocok Krim (Opsional): Jika Anda ingin mencocok whipped cream dengan menggunakan alat khusus.', 'Irish Coffee adalah minuman kopi yang dicampur dengan whiskey Irlandia, gula, dan whipped cream (krim kocok). Berikut adalah bahan-bahan untuk membuat Irish Coffee', 'https://www.youtube.com/watch?v=9xwtCHELxMA', 0, 'Cara membuat Irish Coffee:\r\n\r\n1. Panaskan gelas dengan cara menyiraminya dengan air panas dan biarkan sebentar, lalu buang airnya.\r\n2. Seduh kopi hitam yang cukup kuat dan tuangkan ke dalam gelas pemanas.\r\n3. Tambahkan whiskey Irlandia dan gula ke dalam kopi panas. Aduk hingga gula larut sepenuhnya.\r\n4. Posisikan sendok di atas permukaan kopi, dan perlahan-lahan tuangkan whipped cream yang sudah dikocok secara perlahan di atas sendok. Hal ini akan membuat whipped cream mengapung di atas kopi.\r\n5. Irish Coffee siap disajikan!\r\n', 'irish-original.jpg'),
(16, 'Irish Cream Coffe', 'irish coffe', 'Bahan-bahan untuk membuat Irish Cream Coffee:\r\n\r\n1. Kopi hitam yang kuat (1 cangkir): Pilih kopi yang memiliki rasa kaya dan kuat untuk memberikan dasar yang baik pada minuman.\r\n\r\n2. Whiskey Irlandia (1 1/2 ons atau sekitar 45 ml): Whiskey Irlandia seperti Jameson atau Bushmills umumnya digunakan untuk memberikan rasa khas pada Irish Cream Coffee.\r\n\r\n3. Gula (1 sendok teh, atau sesuai selera): Sesuaikan jumlah gula sesuai dengan preferensi manis Anda.\r\n\r\n4. Irish Cream Liqueur (2 ons atau sekitar 60 ml): Anda dapat menggunakan merek Irish Cream favorit Anda, seperti Baileys.\r\n\r\n5. Whipped cream (krim kocok) yang sudah dikocok kaku: Untuk topping, bisa menggunakan whipped cream yang sudah dikocok hingga kaku.\r\n', 'Alat-alat yang dibutuhkan:\r\n\r\n1. Gelas Pemanas (Irish Coffee Glass): Gelas khusus untuk Irish Coffee yang dapat menahan suhu panas.\r\n\r\n2. Sendok pengaduk: Digunakan untuk mencampur kopi, whiskey, dan gula.\r\n\r\n3. Pemanas Air (Opsional): Jika ingin memanaskan gelas sebelumnya.\r\n\r\n4. Timbangan atau Jigger: Untuk mengukur jumlah whiskey dan Irish Cream Liqueur secara akurat.\r\n', 'Irish Cream Coffee adalah minuman kopi yang disajikan dengan sentuhan whiskey Irlandia dan krim kocok, memberikan kombinasi hangat dan lezat. Berikut adalah keterangan singkat bahan dan alat yang diperlukan:', 'https://www.youtube.com/watch?v=RP8hDCcnzl0', 0, 'Cara membuat Irish Cream Coffee:\r\n\r\n1. Panaskan gelas dengan cara menyiraminya dengan air panas dan biarkan sebentar, lalu buang airnya.\r\n2. Seduh kopi hitam yang cukup kuat dan tuangkan ke dalam gelas pemanas.\r\n3. Tambahkan whiskey Irlandia, Irish Cream Liqueur, dan gula ke dalam kopi panas. Aduk hingga gula larut sepenuhnya.\r\n4. Posisikan sendok di atas permukaan kopi, dan perlahan-lahan tuangkan whipped cream yang sudah dikocok secara perlahan di atas sendok.\r\n5. Irish Cream Coffee siap disajikan!', 'irish-cream.jpg'),
(17, 'Irish Hazelnut Coffe', 'irish coffe', 'Bahan-bahan Hazelnut Irish Coffee:\r\n1. Kopi hitam yang kuat (1 cangkir)\r\n2. Whiskey Irlandia (1 1/2 ons atau sekitar 45 ml)\r\n3. Gula (1 sendok teh, atau sesuai selera)\r\n4. Hazelnut syrup (1-2 sendok teh, atau sesuai selera)\r\n5. Whipped cream (krim kocok) yang sudah dikocok kaku', 'Alat-alat yang dibutuhkan:\r\n1. Gelas Pemanas (Irish Coffee Glass)\r\n2. Sendok pengaduk\r\n3. Sendok tambahkan whipped cream\r\n4. Pemanas Air (Opsional)\r\n5. Mesin Pembuat Kopi atau French Press\r\n6. Timbangan atau Jigger\r\n7. Alat Pencampur atau Sendok Pengocok (Opsional)\r\n8. Alat Pencocok Krim (Opsional)\r\n', 'Hazelnut Irish Coffee menggabungkan cita rasa hazelnut yang kaya dengan kehangatan kopi dan sentuhan whiskey Irlandia. Hazelnut syrup memberikan sentuhan khas pada minuman ini. Pastikan untuk menyesuaikan jumlah hazelnut syrup dan gula sesuai dengan selera Anda. Tambahkan whipped cream di atasnya untuk memberikan kelembutan dan kelezatan ekstra. Selamat menikmati Hazelnut Irish Coffee dengan aroma dan rasa yang menggoda!', 'https://www.youtube.com/watch?v=n_h-xoxU09s', 1, 'Cara membuat Hazelnut Irish Coffee:\r\n1. Panaskan gelas dengan cara menyiraminya dengan air panas dan biarkan sebentar, lalu buang airnya.\r\n2. Seduh kopi hitam yang cukup kuat dan tuangkan ke dalam gelas pemanas.\r\n3. Tambahkan whiskey Irlandia, gula, dan hazelnut syrup ke dalam kopi panas. Aduk hingga gula larut sepenuhnya.\r\n4. Posisikan sendok di atas permukaan kopi, dan perlahan-lahan tuangkan whipped cream yang sudah dikocok secara perlahan di atas sendok.\r\n5. Hazelnut Irish Coffee siap disajikan', 'irish-hazelnut.jpg'),
(18, 'Irish Moka Coffe', 'irish coffe', 'Bahan-bahan Irish Mocha Coffee:\r\n1. Kopi hitam (1 cangkir)\r\n2. Whiskey Irlandia (1 1/2 ons atau sekitar 45 ml)\r\n3. Gula (1 sendok teh, atau sesuai selera)\r\n4. Kakao bubuk (1 sendok makan)\r\n5. Susu cair (1/4 cangkir)\r\n6. Whipped cream (krim kocok) yang sudah dikocok kaku\r\n7. Serbuk cokelat atau cokelat parut (opsional, sebagai hiasan)', 'Alat-alat yang dibutuhkan:\r\n1. Gelas Pemanas (Irish Coffee Glass)\r\n2. Sendok pengaduk\r\n3. Pemanas Air (Opsional)\r\n4. Mesin Pembuat Kopi atau French Press\r\n5. Timbangan atau Jigger\r\n6. Alat Pencampur atau Sendok Pengocok (Opsional)\r\n', 'Irish Mocha Coffee menggabungkan cita rasa kopi yang kuat dengan sentuhan whiskey Irlandia dan kelezatan kakao. Susu cair menambahkan kelembutan pada minuman ini. Pastikan untuk menyesuaikan proporsi bahan sesuai dengan selera Anda dan nikmati Irish Mocha Coffee dengan sentuhan cokelat yang menggoda.', 'https://www.youtube.com/shorts/CagWOmrkKoc', 1, 'Cara membuat Irish Mocha Coffee:\r\n1. Panaskan gelas dengan cara menyiraminya dengan air panas dan biarkan sebentar, lalu buang airnya.\r\n2. Seduh kopi hitam yang cukup kuat dan tuangkan ke dalam gelas pemanas.\r\n3. Tambahkan whiskey Irlandia, gula, kakao bubuk, dan susu cair ke dalam kopi panas. Aduk hingga semua bahan tercampur dengan baik.\r\n4. Posisikan sendok di atas permukaan kopi, dan perlahan-lahan tuangkan whipped cream yang sudah dikocok secara perlahan di atas sendok.\r\n5. Hias dengan serbuk cokelat atau cokelat parut (jika digunakan).\r\n6. Irish Mocha Coffee siap disajikan', 'irish-moka.jpg'),
(19, 'Irish Vanila Coffe', 'irish coffe', 'Bahan-bahan Irish Vanilla Coffee:\r\n1. Kopi hitam (1 cangkir)\r\n2. Whiskey Irlandia (1 1/2 ons atau sekitar 45 ml)\r\n3. Gula (1 sendok teh, atau sesuai selera)\r\n4. Vanilla syrup atau ekstrak vanila (1-2 sendok teh, atau sesuai selera)\r\n5. Susu cair (1/4 cangkir)\r\n6. Whipped cream (krim kocok) yang sudah dikocok kaku\r\n7. Biji vanila sebagai hiasan (opsional)\r\n', 'Alat-alat yang dibutuhkan:\r\n1. Gelas Pemanas (Irish Coffee Glass)\r\n2. Sendok pengaduk\r\n3. Pemanas Air (Opsional)\r\n4. Mesin Pembuat Kopi atau French Press\r\n5. Timbangan atau Jigger\r\n6. Alat Pencampur atau Sendok Pengocok ', 'Irish Vanilla Coffee memberikan sentuhan vanila yang lembut pada kehangatan kopi dan kelezatan whiskey Irlandia. Sesuaikan jumlah vanilla syrup atau ekstrak vanila sesuai dengan selera Anda. Tambahkan whipped cream di atasnya untuk memberikan kelembutan dan kelezatan tambahan. Selamat menikmati Irish Vanilla Coffee dengan aroma dan rasa yang menenangkan.', 'https://www.youtube.com/watch?v=jEUY83gXC8s', 1, 'Cara membuat Irish Vanilla Coffee:\r\n1. Panaskan gelas dengan cara menyiraminya dengan air panas dan biarkan sebentar, lalu buang airnya.\r\n2. Seduh kopi hitam yang cukup kuat dan tuangkan ke dalam gelas pemanas.\r\n3. Tambahkan whiskey Irlandia, gula, vanilla syrup atau ekstrak vanila, dan susu cair ke dalam kopi panas. Aduk hingga semua bahan tercampur dengan baik.\r\n4. Posisikan sendok di atas permukaan kopi, dan perlahan-lahan tuangkan whipped cream yang sudah dikocok secara perlahan di atas sendok.\r\n5. Hias dengan biji vanila (jika digunakan).\r\n6. Irish Vanilla Coffee siap disajikan', 'irish-vanila.jpeg'),
(20, 'Drip Coffe', 'filter coffe', 'Bahan-bahan untuk Drip Coffee:\r\n1. Kopi bubuk (2 sendok makan per cangkir, disesuaikan dengan selera)\r\n2. Air bersih\r\n', 'Alat-alat yang dibutuhkan:\r\n1. Mesin Pembuat Kopi dengan sistem drip\r\n2. Filter kopi (sesuai dengan jenis mesin dan ukuran)\r\n3. Gelas atau termos untuk menampung kopi\r\n', 'Drip Coffee adalah metode penyeduhan kopi yang sederhana dan praktis menggunakan mesin drip. Dengan menggunakan kopi bubuk berkualitas dan memahami preferensi rasio air dan kopi, Anda dapat menikmati secangkir kopi yang lezat dan segar. Jangan lupa untuk menyesuaikan tingkat kehalusan gilingan kopi sesuai dengan mesin dan selera Anda. Selamat menikmati kopi Anda!', 'https://www.youtube.com/watch?v=6OtN5FVSJ9A', 0, 'Cara membuat Drip Coffee:\r\n1. Letakkan filter kopi di dalam keranjang penyaring pada mesin pembuat kopi.\r\n\r\n2. Isi mesin pembuat kopi dengan air bersih sesuai kapasitas yang diinginkan.\r\n\r\n3. Masukkan kopi bubuk ke dalam filter kopi. Gunakan perbandingan yang sesuai dengan selera Anda.\r\n\r\n4. Nyalakan mesin pembuat kopi dan biarkan air panas mengalir melalui kopi bubuk.\r\n\r\n5. Tunggu hingga proses penyaringan selesai. Selama proses ini, air panas akan meresap ke dalam kopi bubuk, mengekstrak rasa dan aroma.\r\n\r\n6. Setelah selesai, buang filter kopi yang sudah digunakan.\r\n\r\n7. Tuangkan kopi yang sudah diseduh ke dalam gelas atau termos.\r\n\r\n8. Nikmati Drip Coffee Anda sebagaimana adanya atau tambahkan gula, susu, atau krim sesuai selera.\r\n', 'drip.jpg'),
(21, 'Aeropress Coffe', 'filter coffe', 'Bahan-bahan untuk AeroPress Coffee:\r\n1. Kopi bubuk (1 hingga 2 sendok makan, tergantung pada selera dan kekuatan yang diinginkan)\r\n2. Air panas (sekitar 175-185 derajat Fahrenheit atau sekitar 80-85 derajat Celsius)\r\n3. Opsional: Gula, susu, atau krim untuk menambahkan rasa\r\n', 'Alat-alat yang dibutuhkan:\r\n1. AeroPress\r\n2. Kertas filter AeroPress\r\n3. Penggiling kopi (opsional, untuk menggiling biji kopi sendiri)\r\n4. Timbangan kopi atau sendok pengukur\r\n5. Teko atau pemanas air\r\n6. Pengaduk atau sendok kayu\r\n7. Gelas atau cangkir\r\n', 'AeroPress adalah metode penyeduhan kopi yang cepat dan fleksibel. Eksperimen dengan rasio air dan kopi serta waktu penyeduhan untuk menemukan cita rasa yang paling Anda sukai. AeroPress menghasilkan kopi yang kaya dan bersih, dan Anda dapat mengatur kekuatan kopi dengan menyesuaikan faktor-faktor tersebut. Selamat menikmati!', 'https://www.youtube.com/watch?v=97VYBfxn2KI', 0, 'Cara membuat AeroPress Coffee:\r\n1. Pasang kertas filter ke dalam tutup bawah AeroPress dan basahi dengan air panas untuk menghilangkan rasa kertas dan memastikan adhesi yang baik.\r\n\r\n2. Tempatkan AeroPress dengan tutup bawah di atas gelas atau cangkir.\r\n\r\n3. Masukkan kopi bubuk ke dalam tabung AeroPress. Jika menggunakan penggiling kopi, pastikan gilingan kopi memiliki kehalusan yang sesuai.\r\n\r\n4. Panaskan air hingga mencapai suhu yang diinginkan.\r\n\r\n5. Tuangkan air panas ke dalam AeroPress dan biarkan kopi meresap (bloom) selama beberapa detik.\r\n\r\n6. Aduk kopi dengan hati-hati selama 10-15 detik menggunakan pengaduk atau sendok kayu.\r\n\r\n7. Pasang tutup atas AeroPress dan tekan perlahan untuk menyeduh kopi ke dalam gelas atau cangkir.\r\n\r\n8. Tambahkan air panas atau bahan tambahan (gula, susu, atau krim) sesuai selera.\r\n\r\n9. Aduk lagi jika diinginkan, dan nikmati AeroPress Coffee Anda!\r\n', 'aeropress.jpg'),
(22, 'Vietnamese Iced Coffe', 'filter coffe', 'Bahan-bahan untuk Vietnamese Iced Coffee:\r\n1. Kopi robusta atau campuran kopi robusta dan arabika (3-4 sendok makan, sangat kasar digiling)\r\n2. Air panas (1/2 cangkir)\r\n3. Susu kental manis (2 hingga 3 sendok makan, sesuai selera)\r\n4. Es batu\r\n', 'Alat-alat yang dibutuhkan:\r\n1. Phin (penyaring tradisional Vietnam) atau French press sebagai alternatif\r\n2. Teko atau pemanas air\r\n3. Gelas tinggi atau cangkir\r\n4. Sendok\r\n', 'Vietnamese Iced Coffee, atau cà phê sữa đá, dikenal karena kekhasannya yang manis dan kuat. Penggunaan kopi robusta memberikan rasa yang khas, dan penggunaan susu kental manis memberikan kelembutan dan kelezatan tambahan. Selamat menikmati secangkir kopi Vietnam yang menyegarkan!', 'https://www.youtube.com/watch?v=WBO866ZdbHg', 1, 'Cara membuat Vietnamese Iced Coffee:\r\n1. Jika menggunakan Phin, pasang lapisan penyaring di dalam, tambahkan kopi yang sudah digiling, dan ratakan permukaannya. Tutup rapat.\r\n\r\n2. Panaskan air hingga mencapai suhu yang hampir mendidih.\r\n\r\n3. Tuangkan sebagian air panas ke dalam phin dan biarkan kopi mekar (bloom) selama 20-30 detik. Setelah itu, tuangkan sisa air.\r\n\r\n4. Tutup phin dan biarkan kopi menyaring selama 5-10 menit hingga selesai.\r\n\r\n5. Ambil segelas tinggi atau cangkir, isi dengan es batu.\r\n\r\n6. Gulingkan susu kental manis di atas es.\r\n\r\n7. Setelah kopi selesai menyaring, tuangkan langsung ke atas susu dan es.\r\n\r\n8. Aduk rata, nikmati Vietnamese Iced Coffee yang segar!\r\n', 'vietnamese.jpg'),
(23, 'Cold Brew Coffe', 'filter coffe', 'Bahan-bahan untuk Cold Brew Coffee:\r\n1. Kopi kasar yang digiling (3/4 hingga 1 cangkir)\r\n2. Air dingin (4 cangkir)\r\n', 'Alat-alat yang dibutuhkan:\r\n1. Wadah besar atau mangkuk\r\n2. Penggiling kopi\r\n3. Filtrasi: kain kopi, saringan kopi kertas, atau alat penyaring cold brew\r\n4. Gelas atau termos untuk menyimpan cold brew\r\n5. Es (opsional)\r\n6. Bahan tambahan seperti susu atau sirup gula (opsional)\r\n', 'Cold Brew Coffee dihasilkan dengan merendam kopi dalam air dingin selama waktu yang lebih lama, menghasilkan minuman yang lebih halus dan rendah asam dibandingkan dengan metode penyeduhan panas. Anda dapat menyesuaikan rasio kopi dan air serta waktu perendaman untuk mencapai kekuatan dan cita rasa yang diinginkan. Cold Brew dapat dinikmati dengan atau tanpa tambahan susu, sirup gula, atau es. Selamat menikmati kesegaran Cold Brew Coffee!', 'https://www.youtube.com/watch?v=An6LvWQuj_8', 1, 'Cara membuat Cold Brew Coffee:\r\n1. Giling kopi kasar menggunakan penggiling kopi.\r\n\r\n2. Campurkan kopi yang sudah digiling dengan air dingin di dalam wadah besar atau mangkuk. Aduk rata untuk memastikan semua kopi terendam.\r\n\r\n3. Tutup wadah atau mangkuk, dan biarkan campuran kopi dan air meresap selama minimal 12 hingga 24 jam di dalam lemari es.\r\n\r\n4. Setelah proses perendaman selesai, saring campuran kopi menggunakan kain kopi, saringan kopi kertas, atau alat penyaring cold brew ke dalam gelas atau termos.\r\n\r\n5. Jika terlalu kuat, encerkan cold brew dengan air atau susu sesuai selera Anda.\r\n\r\n6. Tambahkan es jika diinginkan, dan nikmati Cold Brew Coffee yang lembut dan rendah asam.\r\n', 'coldbrew.jpg'),
(24, 'Indian Filter Coffe', 'filter coffe', 'Bahan-bahan Indian Filter Coffee:\r\n1. Kopi Indian filter (2 hingga 3 sendok makan, campuran robusta dan arabika)\r\n2. Air (1 cangkir)\r\n3. Susu cair (1/2 cangkir hingga 1 cangkir, sesuai selera)\r\n4. Gula (opsional, sesuai selera)\r\n', 'Alat-alat yang dibutuhkan:\r\n1. Indian filter atau percolator\r\n2. Teko atau pemanas air\r\n3. Gelas atau tumbler\r\n', 'Indian Filter Coffee dikenal dengan kekhasannya yang kuat dan kental. Rasio antara kopi dan air, serta jumlah gula dan susu, dapat disesuaikan sesuai dengan selera pribadi. Rasakan aroma khas kopi India dan nikmati kelezatan Indian Filter Coffee yang otentik.', 'https://www.youtube.com/watch?v=w92TS9oERD8', 1, 'Cara membuat Indian Filter Coffee:\r\n1. Panaskan air hingga hampir mendidih.\r\n\r\n2. Letakkan kopi Indian filter di dalam kompartemen atas filter.\r\n\r\n3. Perlahan-lahan tuangkan air panas ke atas kopi dan biarkan proses penyaringan berlangsung. Tunggu hingga air turun melalui filter dan terkumpul di bawahnya.\r\n\r\n4. Sambil menunggu, panaskan susu cair hingga panas (jangan sampai mendidih).\r\n\r\n5. Ambil gelas atau tumbler, tambahkan gula ke dalamnya sesuai selera.\r\n\r\n6. Setelah proses penyaringan selesai, tuangkan kopi yang dihasilkan ke dalam gelas yang berisi gula.\r\n\r\n7. Tambahkan susu panas ke dalam kopi perlahan-lahan sambil menciptakan lapisan krim di permukaan.\r\n\r\n8. Aduk kopi dengan susu dan gula secara merata.\r\n\r\n9. Indian Filter Coffee siap dinikmati!', 'indian.jpg'),
(25, 'Japanese Iced Coffe', 'iced coffe', 'Bahan-bahan untuk Japanese Iced Coffee:\r\n1. Kopi bubuk yang digiling (2 sendok makan)\r\n2. Air panas (1/2 cangkir)\r\n3. Es batu\r\n4. Air dingin (1 cangkir)\r\n5. Gula (opsional, sesuai selera)\r\n6. Susu atau krim (opsional, sesuai selera)\r\n', 'Alat-alat yang dibutuhkan:\r\n1. Pemeras kopi (Hario V60 atau alat serupa)\r\n2. Kertas filter kopi\r\n3. Teko atau pemanas air\r\n4. Gelas atau gelas berisi es\r\n', 'Japanese Iced Coffee melibatkan proses penyeduhan menggunakan air panas langsung ke atas es, menghasilkan minuman yang cepat dan segar. Rasio antara kopi, air, gula, dan susu dapat disesuaikan sesuai dengan preferensi rasa Anda. Selamat menikmati kesegaran Japanese Iced Coffee!', 'https://www.youtube.com/watch?v=AdR5wZVH-H4', 0, 'Cara membuat Japanese Iced Coffee:\r\n1. Pasang kertas filter di dalam pemeras kopi dan letakkan di atas gelas atau gelas yang berisi es.\r\n\r\n2. Giling kopi dan tambahkan ke dalam kertas filter.\r\n\r\n3. Panaskan air hingga mencapai suhu sekitar 200 derajat Fahrenheit (93 derajat Celsius).\r\n\r\n4. Tuangkan sekitar setengah cangkir air panas ke atas kopi yang sudah digiling dan biarkan kopi mekar (bloom) selama 30 detik hingga 1 menit.\r\n\r\n5. Setelah proses perendaman singkat, perlahan-lahan tuangkan sisa air panas secara merata ke atas kopi yang sudah mekar.\r\n\r\n6. Tunggu hingga proses penyaringan selesai.\r\n\r\n7. Pindahkan pemeras kopi dari gelas es, dan tambahkan es batu ke dalamnya.\r\n\r\n8. Jika diinginkan, tambahkan gula dan aduk hingga larut. Kemudian tambahkan susu atau krim sesuai selera.\r\n\r\n9. Aduk rata dan nikmati Japanese Iced Coffee yang segar!\r\n', 'japanese.jpg'),
(26, 'Es Kopi Susu Gula Aren', 'iced coffe', 'Bahan-bahan untuk Es Kopi Susu Gula Aren:\r\n1. Kopi hitam yang kuat, diseduh dan di-dinginkan (1 cangkir)\r\n2. Gula aren cair (sesuai selera)\r\n3. Susu cair (1/2 cangkir hingga 1 cangkir, sesuai selera)\r\n4. Es batu\r\n', 'Alat-alat yang dibutuhkan:\r\n1. Gelas tinggi atau cangkir\r\n2. Sendok pengaduk\r\n', 'Es Kopi Susu Gula Aren menghadirkan kombinasi keharuman kopi, kelembutan susu, dan kelezatan gula aren. Sesuaikan jumlah gula aren dan susu sesuai selera Anda untuk menciptakan minuman yang sempurna sesuai dengan preferensi rasa Anda. Selamat menikmati kesegaran Es Kopi Susu Gula Aren!', 'https://www.youtube.com/watch?v=qpjbAgABI3w', 0, 'Cara membuat Es Kopi Susu Gula Aren:\r\n1. Sediakan es batu dan letakkan di dalam gelas tinggi atau cangkir.\r\n\r\n2. Tuangkan kopi hitam yang sudah diseduh dan didinginkan ke atas es batu.\r\n\r\n3. Tambahkan gula aren cair sesuai selera. Aduk hingga larut.\r\n\r\n4. Tuangkan susu cair ke atas campuran kopi dan es. Aduk kembali hingga semua bahan tercampur rata.\r\n\r\n5. Jika diinginkan, tambahkan lebih banyak es batu untuk menjaga kesegaran minuman.\r\n\r\n6. Es Kopi Susu Gula Aren siap dinikmati!\r\n', 'gulaaren.jpg'),
(27, 'Iced Coffe Hokkaido', 'iced coffe', 'Bahan-bahan untuk Iced Coffee Hokkaido:\r\n1. Kopi hitam yang kuat, diseduh dan di-dinginkan (1 cangkir)\r\n2. Susu kental manis (2-3 sendok makan)\r\n3. Susu evaporasi (1/4 cangkir)\r\n4. Sirup vanila (1-2 sendok teh)\r\n5. Es batu\r\n', 'Alat-alat yang dibutuhkan:\r\n1. Gelas tinggi atau cangkir\r\n2. Sendok pengaduk\r\n', 'Iced Coffee Hokkaido adalah minuman kopi dingin yang memadukan kekentalan susu kental manis, kelembutan susu evaporasi, dan keharuman vanila. Sesuaikan jumlah susu dan sirup vanila sesuai selera Anda untuk mencapai rasa yang sempurna. Nikmati sensasi Iced Coffee Hokkaido yang unik dan lezat!', 'https://www.youtube.com/watch?v=yQBtQFMPtzo', 1, 'Cara membuat Iced Coffee Hokkaido:\r\n1. Siapkan es batu dan letakkan di dalam gelas tinggi atau cangkir.\r\n\r\n2. Tuangkan kopi hitam yang sudah diseduh dan didinginkan ke atas es batu.\r\n\r\n3. Tambahkan susu kental manis ke dalam kopi. Aduk hingga rata.\r\n\r\n4. Tuangkan susu evaporasi ke dalam gelas secara perlahan untuk menciptakan lapisan lembut di atas kopi.\r\n\r\n5. Tambahkan sirup vanila ke dalam campuran. Aduk kembali hingga rata.\r\n\r\n6. Jika diinginkan, tambahkan lebih banyak es batu untuk menjaga kesegaran minuman.\r\n\r\n7. Iced Coffee Hokkaido siap dinikmati!\r\n', 'hokkaido.jpg'),
(28, 'Iced Coffe Aceh', 'iced coffe', 'Bahan-bahan untuk Iced Coffee Aceh:\r\n1. Kopi Aceh yang berkualitas tinggi, diseduh dan di-dinginkan (1 cangkir)\r\n2. Gula aren atau madu Aceh (sesuai selera)\r\n3. Es batu\r\n4. Air (opsional, untuk penyeimbang kekuatan kopi)\r\n5. Susu kental manis (opsional, sesuai selera)\r\n', 'Alat-alat yang dibutuhkan:\r\n1. Gelas atau cangkir\r\n2. Sendok pengaduk\r\n', 'Iced Coffee Aceh menonjolkan kekhasan kopi Aceh yang memiliki karakter kuat dan bercitarasa. Penggunaan gula aren atau madu Aceh memberikan sentuhan lokal yang khas. Sesuaikan tingkat kekuatan kopi dan kelembutan dengan menambahkan air atau susu sesuai dengan selera pribadi Anda. Selamat menikmati kelezatan Iced Coffee Aceh yang segar dan unik!', 'https://www.youtube.com/watch?v=0lXSZd_kXVA', 1, 'Cara membuat Iced Coffee Aceh:\r\n1. Sediakan es batu dan letakkan di dalam gelas atau cangkir.\r\n\r\n2. Tuangkan kopi Aceh yang sudah diseduh dan didinginkan ke atas es batu.\r\n\r\n3. Tambahkan gula aren atau madu Aceh sesuai selera. Aduk hingga larut.\r\n\r\n4. Jika diinginkan, tambahkan susu kental manis untuk memberikan kelembutan dan kelezatan tambahan.\r\n\r\n5. Jika kopi terlalu kuat, tambahkan air untuk menyeimbangkan kekuatan rasa.\r\n\r\n6. Aduk kembali hingga semua bahan tercampur rata.\r\n\r\n7. Iced Coffee Aceh siap dinikmati!\r\n', 'aceh.jpg');
INSERT INTO `coffe` (`id_coffe`, `nama_coffe`, `jenis_coffe`, `bahan_bahan`, `alat_alat`, `keterangan`, `link_vidio`, `status`, `cara_pembuatan`, `gambar`) VALUES
(29, 'Iced Coffe Thai', 'iced coffe', 'Bahan-bahan untuk Thai Coffee:\r\n1. Kopi hitam yang kuat, diseduh dan di-dinginkan (1 cangkir)\r\n2. Susu kental manis (2-3 sendok makan)\r\n3. Susu evaporasi (2 sendok makan)\r\n4. Gula (sesuai selera)\r\n5. Es batu\r\n', 'Alat-alat yang dibutuhkan:\r\n1. Gelas atau cangkir\r\n2. Sendok pengaduk\r\n', 'Thai Coffee memiliki keunikan dengan kombinasi kekentalan susu kental manis, kelembutan susu evaporasi, dan sentuhan manis dari gula. Penggunaan kopi hitam yang kuat memberikan karakter yang khas. Sesuaikan jumlah gula dan susu sesuai selera Anda untuk mencapai rasa yang sempurna. Nikmati sensasi Thai Coffee yang lezat dan segar!', 'https://www.youtube.com/watch?v=DtXjQ8ffr2k', 1, 'Cara membuat Thai Coffee:\r\n1. Siapkan es batu dan letakkan di dalam gelas atau cangkir.\r\n\r\n2. Tuangkan kopi hitam yang sudah diseduh dan didinginkan ke atas es batu.\r\n\r\n3. Tambahkan susu kental manis ke dalam kopi. Aduk hingga rata.\r\n\r\n4. Tuangkan susu evaporasi ke dalam gelas secara perlahan untuk menciptakan lapisan lembut di atas kopi.\r\n\r\n5. Tambahkan gula sesuai selera. Aduk kembali hingga larut.\r\n\r\n6. Jika diinginkan, tambahkan lebih banyak es batu untuk menjaga kesegaran minuman.\r\n\r\n7. Thai Coffee siap dinikmati!\r\n', 'thai.jpg'),
(30, 'Iced Coffe Greek Frappe', 'iced coffe', 'Bahan-bahan untuk Greek Frappe Iced Coffee:\r\n1. Kopi instan (2-3 sendok teh)\r\n2. Air dingin (1/4 cangkir)\r\n3. Gula (sesuai selera)\r\n4. Es batu\r\n5. Susu cair (opsional)\r\n6. Air dingin tambahan (opsional)\r\n', 'Alat-alat yang dibutuhkan:\r\n1. Shaker atau blender\r\n2. Gelas tinggi atau cangkir\r\n3. Sedotan (opsional)\r\n', 'Greek Frappe Iced Coffee memiliki tekstur ringan dan rasa yang kaya. Proses pengocokan atau blending menciptakan busa lembut yang memberikan sentuhan unik pada minuman ini. Sesuaikan tingkat kekentalan dan manis dengan menyesuaikan jumlah kopi, gula, dan susu sesuai dengan selera Anda. Nikmati kesegaran Greek Frappe Iced Coffee yang lezat!', 'https://www.youtube.com/watch?v=MsL8n-u4CSc', 1, 'Cara membuat Greek Frappe Iced Coffee:\r\n1. Di dalam shaker atau blender, campurkan kopi instan, air dingin, dan gula sesuai selera.\r\n\r\n2. Kocok atau blender campuran tersebut dengan cepat selama 15-20 detik, atau hingga menghasilkan busa yang lebat.\r\n\r\n3. Sediakan es batu di dalam gelas tinggi atau cangkir.\r\n\r\n4. Tuangkan campuran kopi instan yang sudah dikocok ke atas es batu.\r\n\r\n5. Jika diinginkan, tambahkan susu cair ke dalam minuman.\r\n\r\n6. Jika ingin lebih encer, tambahkan air dingin tambahan sesuai selera.\r\n\r\n7. Aduk rata dengan sedotan atau sendok.\r\n\r\n8. Greek Frappe Iced Coffee siap dinikmati!\r\n', 'greek.jpg'),
(31, 'Iced Affogato Freddo Scoop Coffe', 'iced coffe', 'Bahan-bahan untuk Iced Coffee Affogato Freddo Scoop Coffee:\r\n1. Es krim vanilla (2 scoop)\r\n2. Kopi hitam yang kuat, diseduh dan di-dinginkan (1/2 cangkir)\r\n3. Gula (opsional)\r\n4. Es batu\r\n5. Bubuk kakao atau serutan cokelat (opsional, sebagai hiasan)\r\n', 'Alat-alat yang dibutuhkan:\r\n1. Gelas atau cangkir\r\n2. Sendok pengaduk\r\n', 'Iced Coffee Affogato Freddo Scoop Coffee menggabungkan kelezatan es krim vanilla dengan keharuman dan kekuatan kopi hitam yang kuat. Sesuaikan tingkat keasaman dan kekentalan dengan menambahkan atau mengurangi gula sesuai selera Anda. Hias minuman dengan bubuk kakao atau serutan cokelat untuk tampilan yang menarik. Nikmati kesegaran dan kelezatan dari Iced Coffee Affogato Freddo Scoop Coffee!', 'https://www.youtube.com/watch?v=bCXSOJVO7iQ', 1, 'Cara membuat Iced Coffee Affogato Freddo Scoop Coffee:\r\n1. Letakkan es krim vanilla ke dalam gelas atau cangkir.\r\n\r\n2. Tuangkan kopi hitam yang sudah diseduh dan didinginkan ke atas es krim vanilla.\r\n\r\n3. Tambahkan gula jika diinginkan. Aduk rata.\r\n\r\n4. Sediakan es batu dan tambahkan ke dalam minuman.\r\n\r\n5. Hias dengan bubuk kakao atau serutan cokelat (jika digunakan).\r\n\r\n6. Iced Coffee Affogato Freddo Scoop Coffee siap dinikmati!\r\n', 'affogato.jpeg');

-- --------------------------------------------------------

--
-- Table structure for table `pengguna`
--

CREATE TABLE `pengguna` (
  `id_pengguna` int(11) NOT NULL,
  `nama_lengkap` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  `provinsi` varchar(50) NOT NULL,
  `kota` varchar(50) NOT NULL,
  `kecamatan` varchar(50) NOT NULL,
  `rt` varchar(5) NOT NULL,
  `rw` varchar(5) NOT NULL,
  `kelurahan` varchar(50) NOT NULL,
  `agama` varchar(20) NOT NULL,
  `jenis_kelamin` varchar(20) NOT NULL,
  `tanggal_lahir` date NOT NULL,
  `alamat` text NOT NULL,
  `status` int(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `pengguna`
--

INSERT INTO `pengguna` (`id_pengguna`, `nama_lengkap`, `email`, `password`, `provinsi`, `kota`, `kecamatan`, `rt`, `rw`, `kelurahan`, `agama`, `jenis_kelamin`, `tanggal_lahir`, `alamat`, `status`) VALUES
(1, 'ALIF NURFIRDAUS', 'muhammadalif1234@gmail.com', '3252bba41728b8de239834eb434dd21c', 'JAWA BARAT', 'BANDUNG', 'COBLONG', '03', '01', 'SEKELOA', 'ISLAM', 'LAKI - LAKI', '2003-12-27', 'Jl. Dipati Ukur No.112-116, Lebakgede Kecamatan Coblong, Kota Bandung, Jawa Barat 40132', 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `coffe`
--
ALTER TABLE `coffe`
  ADD PRIMARY KEY (`id_coffe`);

--
-- Indexes for table `pengguna`
--
ALTER TABLE `pengguna`
  ADD PRIMARY KEY (`id_pengguna`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `coffe`
--
ALTER TABLE `coffe`
  MODIFY `id_coffe` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=32;

--
-- AUTO_INCREMENT for table `pengguna`
--
ALTER TABLE `pengguna`
  MODIFY `id_pengguna` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
